In [123]:
import numpy as np

## Datatypes & Attributes

In [124]:
# Numpy's main datatype is ndarray.
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [125]:
type(a1)

numpy.ndarray

In [126]:
a2 = np.array([[1, 2, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [127]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [128]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [129]:
a1.shape

(3,)

In [130]:
a2.shape


(2, 3)

In [131]:
a3.shape


(2, 3, 3)

In [132]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [133]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [134]:
a1.size, a2.size, a3.size


(3, 6, 18)

In [135]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [136]:
#create a Dataframe from Numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Numpy array

In [137]:
sample_array = np.array([1, 2,3])
sample_array

array([1, 2, 3])

In [138]:
sample_array.dtype

dtype('int32')

In [139]:
ones = np.ones((2,3))

In [140]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [141]:
ones.dtype


dtype('float64')

In [142]:
type(ones)

numpy.ndarray

In [143]:
zeros = np.zeros((2,3))

In [144]:
zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [145]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [146]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[0, 5, 3, 0, 5],
       [7, 1, 8, 4, 9],
       [0, 2, 0, 7, 6]])

In [147]:
random_array.size

15

In [148]:
random_array.shape

(3, 5)

In [149]:
random_array_2 = np.random.random((5,3))

In [150]:
random_array_2

array([[0.55054305, 0.52259111, 0.48755248],
       [0.26303148, 0.52728579, 0.98446573],
       [0.62342345, 0.62955693, 0.9099729 ],
       [0.96251949, 0.5850998 , 0.16489774],
       [0.39159332, 0.94455493, 0.34339118]])

In [151]:
random_array_2.shape

(5, 3)

In [152]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.70507037, 0.4628868 , 0.38679069],
       [0.52843256, 0.82168992, 0.63847702],
       [0.86288872, 0.63662654, 0.99929706],
       [0.51778008, 0.32761664, 0.09877324],
       [0.5667664 , 0.21520794, 0.01179079]])

In [153]:
#Pseudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size = (5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [154]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [155]:
random_array_4.shape

(5, 3)

## 3. Viewing Arrays and Matrices

In [156]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
a1

array([1, 2, 3])

In [158]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [159]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [160]:
a1[0]

1

In [161]:
a2[0]

array([1. , 2. , 3.3])

In [162]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
a2[1]

array([4. , 5. , 6.5])

In [164]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [165]:
a4 = np.random.randint(10, size =(2, 3, 4, 5))

In [166]:
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [167]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [168]:
#get the first 4 numbers of the iner most array
a4[:, :, :, :2]

array([[[[3, 5],
         [5, 0],
         [9, 6],
         [3, 3]],

        [[1, 0],
         [7, 9],
         [7, 7],
         [3, 1]],

        [[4, 3],
         [9, 1],
         [2, 5],
         [9, 9]]],


       [[[3, 0],
         [7, 2],
         [6, 6],
         [7, 1]],

        [[9, 9],
         [6, 8],
         [6, 1],
         [9, 8]],

        [[7, 5],
         [8, 1],
         [3, 7],
         [7, 5]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [169]:
a1


array([1, 2, 3])

In [170]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [171]:
a1 + ones

array([2., 3., 4.])

In [172]:
a1 - ones

array([0., 1., 2.])

In [173]:
a1 * ones

array([1., 2., 3.])

In [174]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [175]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [176]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [177]:
# how can you reshape a2 to be compatible with a3?
# search "how to reshape numpy array"
a3 * a2

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,3) 

In [ ]:
a1 / ones

In [ ]:

# floor division removes the decimals(round down)
a2 // a1

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
a1 % 2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

## Aggregation

#  Aggregation = performing the same operation on a number of things

In [ ]:
listy_list = [1, 2, 3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
a1

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

#  use python's method (`sum()`) on python datatypes and use 
# Numpy's methods on Numpy Arrays (`np.sum())

In [ ]:
# creative a massive Numpy array
massive_array  = np.random.random(100000)
massive_array

In [ ]:
massive_array[:10
             ]

In [ ]:
%timeit sum(massive_array)# Python's sum()
%timeit np.sum(massive_array) # Numpy np.sum

In [ ]:
# this how much faster than python
17900 / 34

In [ ]:
a2 

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard deviation = a measure of how spread out a groups of numbers is far apart
np.std(a2)

In [ ]:
# variance = measure of the average degree to which each number is different to the mean
#Higher variance = wider range of numbers
# lower variance = lower range of the number.
np.var(a2)

In [ ]:
#standard deviation = sqre root of variance
np.sqrt(np.var(a2))


In [ ]:
#Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array =np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show

### Reshaping & transposing

In [ ]:
a2


In [ ]:
a2

In [ ]:
a3

In [ ]:
a2 * a3

In [ ]:
a2.reshape(2,3,1).shape

In [ ]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
# transpose
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3.shape


In [ ]:
a3.T.shape

## Dot product

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# element_wise multiplication(hadamard product)
mat1 * mat2

In [ ]:
# dot product
np.dot(mat1, mat2)

In [ ]:
# transpose mat1
mat1.T

In [ ]:
mat2.shape

In [ ]:
mat2.shape, mat1.T.shape


In [ ]:
mat1.shape, mat2.T.shape

In [ ]:
mat3 = np.dot(mat1, mat2.T)

In [ ]:
mat3

In [ ]:
mat3.shape

In [ ]:
## Dot product example (nut butter sales)
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

In [ ]:
#create weekly_sales DatRAME
weekly_sales = pd.DataFrame(sales_amounts, 
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"], 
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

In [ ]:
# create the prices
prices =np.array([10, 8, 12])
prices

In [ ]:
prices.shape

In [ ]:
#create dagtafrome prices
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["prices"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

In [ ]:
total_sales = prices.dot(sales_amounts)

In [ ]:
# shape not aligne
total_sales = prices.dot(sales_amounts.T)
total_sales

In [ ]:
# create daily sales
butter_prices.shape, weekly_sales.shape

In [ ]:
weekly_sales.T.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.shape

In [ ]:
weekly_sales.shape

In [ ]:
weekly_sales

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

### Comparison Operators

In [ ]:
a2

In [ ]:
a1 > a2

In [ ]:
bool_array = a1 >= a2
bool_array

In [ ]:
type(bool_array), bool_array.dtype

In [ ]:
a1 > 5 

In [ ]:
a1 < 5

In [ ]:
a1 == a1

## 5. sorting array

random_array = np.random.randint(10 , size=(3, 5))

In [ ]:
random_array = np.random.randint(10 , size=(3, 5))
random_array

In [ ]:
random_array.shape


In [ ]:
np.sort(random_array)

In [ ]:
np.argsort(random_array)

In [ ]:
np.argsort(a1)

In [ ]:
np.argmin(a1)

In [ ]:
np.argmax(a1)

In [ ]:
random_array

In [ ]:
np.argmax(random_array, axis=0)

## 6. Practical Example - Numpy in action!!!


<img src="panda.png">
![panda.png](attachment:panda.png)


# Turn an image into a NumPy array




In [188]:
from matplotlib.image import imread

panda = imread('panda.png')
print(type(panda))


<class 'numpy.ndarray'>


In [189]:
panda.shape

(2330, 3500, 3)

In [191]:
panda.size, panda.shape, panda.ndim


(24465000, (2330, 3500, 3), 3)

In [192]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="car-photo.png">/

In [193]:
car = imread("car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [195]:
car[:3]


array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

<image src="dog-photo.png"/>

<img src="dog-photo.png"/>

In [199]:
dog = imread("dog-photo.png")
print(type(dog))

<class 'numpy.ndarray'>


In [200]:
car[:1
   ]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)